// <auto-generated>
//   Generated by UnityProject/Tools/art2d/build_assets.py - do not edit by hand.
//   Sprite rectangles inside Assets/Resources/Art/PixelArt/*.png.
// </auto-generated>
using System.Collections.Generic;
using UnityEngine;

namespace Subsistence
{
    /// <summary>Lookup table for the painted 2D pixel-art atlases.</summary>
    public static class PixelArtAtlas
    {
        public struct Entry
        {
            public string name;
            public string texture;
            public float x, y, w, h;
            public float pivotX, pivotY;
            public float pixelsPerUnit;
        }

        public static readonly Entry[] All =
        {
            new Entry { name = "watcher_attack", texture = "characters", x = 0f, y = 0f, w = 224f, h = 152f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "survivor_attack", texture = "characters", x = 226f, y = 0f, w = 127f, h = 150f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "watcher_idle", texture = "characters", x = 355f, y = 0f, w = 83f, h = 150f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "trader", texture = "characters", x = 440f, y = 0f, w = 107f, h = 148f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "survivor_walk_a", texture = "characters", x = 549f, y = 0f, w = 62f, h = 146f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "survivor_idle", texture = "characters", x = 613f, y = 0f, w = 52f, h = 144f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "survivor_walk_b", texture = "characters", x = 667f, y = 0f, w = 54f, h = 144f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "survivor_pack", texture = "characters", x = 723f, y = 0f, w = 52f, h = 144f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "survivor_jump", texture = "characters", x = 777f, y = 0f, w = 78f, h = 140f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "door", texture = "props", x = 0f, y = 0f, w = 174f, h = 240f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "elevator_closed", texture = "props", x = 176f, y = 0f, w = 150f, h = 224f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "elevator_open", texture = "props", x = 328f, y = 0f, w = 150f, h = 224f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "workbench_2", texture = "props", x = 480f, y = 0f, w = 128f, h = 112f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "workbench_3", texture = "props", x = 610f, y = 0f, w = 128f, h = 112f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "crate_2", texture = "props", x = 740f, y = 0f, w = 104f, h = 96f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "crate_3", texture = "props", x = 846f, y = 0f, w = 104f, h = 96f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "workbench_1", texture = "props", x = 0f, y = 242f, w = 160f, h = 80f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "crate_1", texture = "props", x = 162f, y = 242f, w = 128f, h = 67f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "placard", texture = "props", x = 292f, y = 242f, w = 72f, h = 48f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "lamp", texture = "props", x = 366f, y = 242f, w = 150f, h = 44f, pivotX = 0.5f, pivotY = 1.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "keycard", texture = "props", x = 518f, y = 242f, w = 44f, h = 44f, pivotX = 0.5f, pivotY = 0.5f, pixelsPerUnit = 96.0f },
            new Entry { name = "outlet", texture = "props", x = 564f, y = 242f, w = 40f, h = 34f, pivotX = 0.5f, pivotY = 0.0f, pixelsPerUnit = 96.0f },
            new Entry { name = "pipe", texture = "props", x = 606f, y = 242f, w = 192f, h = 28f, pivotX = 0.5f, pivotY = 0.5f, pixelsPerUnit = 96.0f },
        };

        static readonly Dictionary<string, Entry> Index = BuildIndex();

        static Dictionary<string, Entry> BuildIndex()
        {
            var map = new Dictionary<string, Entry>(All.Length);
            for (int i = 0; i < All.Length; i++) map[All[i].name] = All[i];
            return map;
        }

        public static bool TryGet(string name, out Entry entry) => Index.TryGetValue(name, out entry);

        /// <summary>Creates (and caches) a sprite from an atlas entry.</summary>
        public static Sprite Load(string name)
        {
            if (!TryGet(name, out Entry e)) return null;
            if (Cache.TryGetValue(name, out Sprite cached) && cached != null) return cached;
            Texture2D texture = Resources.Load<Texture2D>("Art/PixelArt/" + e.texture);
            if (texture == null) return null;
            texture.filterMode = FilterMode.Point;
            texture.wrapMode = TextureWrapMode.Clamp;
            Rect rect = new Rect(e.x, texture.height - e.y - e.h, e.w, e.h);
            Sprite sprite = Sprite.Create(texture, rect, new Vector2(e.pivotX, e.pivotY),
                e.pixelsPerUnit, 0, SpriteMeshType.FullRect, Vector4.zero, false);
            sprite.name = name;
            Cache[name] = sprite;
            return sprite;
        }

        static readonly Dictionary<string, Sprite> Cache = new Dictionary<string, Sprite>();
    }
}
